services:
  mongo:
    image: mongo
    container_name: fleetlink-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: fleetlink-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongo:27017/fleetlink
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: fleetlink-frontend
    ports:
      - "3000:80"  # Host port 3000 -> Container port 80 (served by NGINX)
    depends_on:
      - backend
    # No need for working_dir or command, nginx handles it

volumes:
  mongo-data:
